name: SekQRen
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  mobile_scanner: ^5.1.1
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  path_provider: ^2.1.5
  open_file: ^3.5.10
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_app_name: ^0.1.1

# --- TAMBAHKAN BAGIAN INI UNTUK MENGATASI KONFLIK ---
dependency_overrides:
  xml: ^6.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_app_name:
  name: "SekQRen"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21